fos_user_security:
    resource: "@FOSUserBundle/Resources/config/routing/security.xml"

vm_client_area:
    resource: "@VMClientAreaBundle/Resources/config/routing.yml"
    prefix:   /

vm_core:
    resource: "@VMCoreBundle/Resources/config/routing.yml"
    prefix:   /
