parameters:
#    vm_core.example.class: VM\CoreBundle\Example

services:
#    vm_core.example:
#        class: %vm_core.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
    vm_core.menu_builder:
        class: VM\CoreBundle\Menu\MenuBuilder
        arguments: ["@knp_menu.factory"]

    vm_core.menu.main:
        class: Knp\Menu\MenuItem
        factory_service: vm_core.menu_builder
        factory_method: createMainMenu
        arguments: ["@request"]
        scope: request
        tags:
            - { name: knp_menu.menu, alias: main }
