#TO BE REMOVED IN PRODUCTION ENVIRONEMENT
client_area_switch_role:
    pattern:  /switch-role
    defaults: { _controller: VMClientAreaBundle:Account:switchRole }
    
  
client_area_profile_view:
    pattern:  /profile
    defaults: { _controller: VMClientAreaBundle:Account:viewProfile }
